### ISSUE TITLE
Unable to activate extension

### ISSUE THREAD

**Issue by knservis** [MattthiasSchedel/bibtex-fetcher#1]
Hi @MattthiasSchedel , 

thank you for this very interesting extension. Unfortunately, I have been unable to try it as on activation the following occurs:

```
Cannot find module './fetchBibTeX'
... .vscode-server/extensions/matthiasschedel.bibtex-manager-3.2.0/out/SearchBTViewProvider.js
```

Running on:

```
Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22000
```

And the extension is on WSL (ubuntu)

Thank you

**Comment by MattthiasSchedel** [comment]
Hi @knservis , Thank you for your interest in this extension. 

Just for my understanding, You are running VSCode on Windows Subsystem for Linux? Is there a reason for not running it directly on your Windows Machine?

I have not encountered this error yet so i will try to recreate your setup. 

The only differences to my system i can see is in the operating system.

**Comment by knservis** [comment]
Hi Matthias,

It is a personal preference. Even the idea doing work outside WSL is terrifying to me as I have plenty of negative experiences from Win. I just use the Win UI on my writing/email laptop as it is convenient and it has recently, with the addition of WSL scraped below the "unnaceptable" bar. I cannot imagine that doing work on WSL is uncommon though or my case unique. 

HTH
  
Ενεργοποίηση 27.10.2023 6:38:31 μμ, Matthias Schedel ***@***.***> έγραψε:
Hi @knservis [https://github.com/knservis] , Thank you for your interest in this extension.
Just for my understanding, You are running VSCode on Windows Subsystem for Linux? Is there a reason for not running it directly on your Windows Machine?
I have not encountered this error yet so i will try to recreate your setup.
The only differences to my system i can see is in the operating system.

**Comment by MattthiasSchedel** [comment]
So you are running VS code like this: https://code.visualstudio.com/docs/remote/wsl? 

To be honest this seems to be quite a edge case scenario. I would love to fix the extension to help users running VS code similarly but it is impossible for me to recreate this error. 

Do you have problems with other extensions or just this one?

This is a wild guess on what is happening: 
If you have VSCode running like in the following image, i could imagine that when you installed the extension (with the windows part of VS code), and you try to run the fetchBibtex command it somehow looks for that in the WSL VS codes file system? 
![image](https://github.com/MattthiasSchedel/bibtex-fetcher/assets/44608861/11a97d5f-e648-423c-90ae-69920747bc2b)]

It just does not make a lot of sense to me that the extension would randomly drop a file form its code. 

I will look into precompiling the javascript because i could imagine that bundles everything more tightly..

You could also just fork the repository and try to build the extension locally. Maybe that helps.

**Comment by MattthiasSchedel** [comment]
I will close the Issue since you are not responding. I hope you found a solution.
